language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

script:
 - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/LANIMFE/ApproximationGrids.jl.git")); Pkg.instantiate()'
 - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/LANIMFE/LiquidsStructure.jl.git")); Pkg.instantiate()'
 - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/LANIMFE/LiquidsDynamics.jl.git")); Pkg.instantiate()'
 - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
